// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"api/graph/models"
)

type Label struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type NewTodo struct {
	Title       string  `json:"title"`
	Description *string `json:"description"`
}

type Priority struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type SearchTodo struct {
	Column string `json:"column"`
	Value  string `json:"value"`
}

type SortTodo struct {
	Column string `json:"column"`
	Value  string `json:"value"`
}

type Status struct {
	ID    string         `json:"id"`
	Name  string         `json:"name"`
	Todos []*models.Todo `json:"todos"`
}

type User struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Todos     []*models.Todo `json:"todos"`
	SortTodos []*models.Todo `json:"sortTodos"`
}
